name: Deploy FastAPI to AWS EC2

on:
  push:
    branches:
    - main # O deploy será disparado em pushs na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do repositório
    - name: Checkout Code
      uses: actions/checkout@v3
    # Configuração do Node.js versão 16
    - name: Set up Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    # Instalar dependências (caso precise)
    - name: Install dependencies
      run: |
        npm install

    # 2. Configuração de acesso SSH ao EC2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }} # Configure essa chave em Settings > Secrets do GitHub

    # 3. Deploy do código para o EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/access-control-api  # Mude para o diretório do seu app
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          # Reinicie o servidor ou o processo (exemplo: gunicorn, uvicorn, etc.)
          sudo systemctl restart fastapi.service
        EOF
    - name: Debug SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'echo "SSH successful"'
