name: Deploy FastAPI to EC2

on:
  push:
    branches:
    - main # Altere para o branch que deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar chave SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy para EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.17.172.7 << 'EOF'
          cd /home/ubuntu/seu-repositorio || {
            echo "Clonando repositório pela primeira vez..."
            git clone https://github.com/seu-usuario/seu-repositorio.git
            cd seu-repositorio
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
          }
          echo "Atualizando repositório..."
          cd /home/ubuntu/seu-repositorio
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
        EOF
