name: Deploy FastAPI

on:
  push:
    branches:
    - main # Ou o branch principal do seu projeto

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar acesso SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Fazer deploy na instância EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@EC2_IP << EOF
          cd /home/ubuntu/access-control
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
        EOF
